[package]
name = "openvino-sys"
version = "0.1.0"
license = "Apache-2.0"
description = "Low-level bindings for OpenVINO (use the `openvino` crate for easier-to-use bindings)."
authors = ["OpenVINO Project Developers"]
repository = "https://github.com/openvinotoolkit/openvino"
homepage = "https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/ie_bridges/rust"
documentation = "https://docs.rs/openvino-sys"
edition = "2018"
include = [
    "/Cargo.toml",
    "/README.md",
    "/build.rs",
    "/src",
    # Since it is quite difficult to fit OpenVINO into the 10MB crate limit, this crate is published with only the
    # sources necessary for bindgen to build the Rust bindings. This means that the crate can only be either:
    # - built from OpenVINO sources when built as the primary crate (unlikely usage)
    # - built from an OpenVINO installation when used as a dependency
    "/upstream/inference-engine/ie_bridges/c/include",
]

[build-dependencies]
bindgen = "0.55.1"
cmake = "0.1.44"

[features]
default = ["cpu"]
all = ["cpu", "gpu", "gna", "hetero", "multi", "myriad"]
cpu = []
gpu = []
gna = []
hetero = []
multi = []
myriad = []
